FROM php:8.0-apache

COPY ./config/000-default.conf /etc/apache2/sites-available/000-default.conf
COPY ./config/start-apache /usr/local/bin/start-apache
RUN a2enmod rewrite

COPY ./ /var/www/

RUN groupadd apache-www-volume -g 1000
RUN useradd apache-www-volume -u 1000 -g 1000

RUN apt-get update && apt-get -y install curl && apt-get -y clean

CMD ["apache2-foreground"]
