version: "3.9"

services:
  frontend:
    build:
      dockerfile: Dockerfile.frontend
      context: ./frontend/
    container_name: bshare_application
    profiles: ["dev", "dev-frontend"]
    ports:
      - 3000:80
    volumes:
      - ./frontend/:/var/www/
      - ./frontend/config/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./frontend/config/start-apache:/usr/local/bin/start-apache
    environment:
      Webservice_HOST: bshare_webservice
      APP_ENV: development
      APACHE_RUN_USER: apache-www-volume
      APACHE_RUN_GROUP: apache-www-volume
      APP_KEY: SomeRandomStringToAddSecurity123

  backend:
    build:
      dockerfile: Dockerfile.backend
      context: ./server/
    container_name: bshare_webservice
    profiles: ["dev", "dev-backend"]
    depends_on:
      - mysql
    ports:
      - 3200:80
    volumes:
      - ./server/:/var/www/html/
      - ./server/config/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./server/config/start-apache:/usr/local/bin/start-apache
    environment:
      MYSQL_HOST: bshare_database
      MYSQL_USER: root
      MYSQL_PASSWORD: bshare
      MYSQL_DB: db_bshare

  mysql:
    image: mysql:8.0.23
    container_name: bshare_database
    profiles: ["dev", "dev-backend", "deploy"]
    ports:
      - 3309:3306
    volumes:
      - bshare-database:/var/lib/mysql
    environment:
      MYSQL_USER: CANELA
      MYSQL_PASSWORD: canela
      MYSQL_ROOT_PASSWORD: bshare
      MYSQL_DATABASE: db_bshare

volumes:
  bshare-database:
