FROM php:7.4-apache

COPY ./ /var/www/html/
COPY ./config/000-default.conf /etc/apache2/sites-available/000-default.conf
COPY ./config/start-apache /usr/local/bin/start-apache

RUN a2enmod rewrite
RUN docker-php-ext-install pdo pdo_mysql